### ISSUE TITLE
Not working on Win10

### ISSUE THREAD

**Issue by themre** [d4rkr00t/aik#75]
Hi,
I tried AIK on my machine (win10, node 6+) and when trying to run aik index.js -c -r, i get this error:
`Warning in c:/Users/Trebizan/AppData/Roaming/npm/~/aik/~/webpack/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.`

I'm thinking it has something to do with this? https://github.com/webpack/webpack/issues/2362
Thanks!

**Comment by d4rkr00t** [comment]
Hi, 
Looks like it's exactly same problem as described in webpack issue.

Could you, please try to cd into "C:/Users/Trebizan/..." with capital "C" and check whether this still an issue or not?

And I'll try to find any windows pc to check it myself.

**Comment by themre** [comment]
I tested it and it works with both c: and C:. I just needed to replace ~ with node_modules. I also noticed that in console I don't get URL to open in browser like in your demo: 
`     Frontend Playground

CSS Modules:       enabled
Ngrok:             disabled
React Hot Loader:  enabled`

**Comment by d4rkr00t** [comment]
The url should be on top of your terminal when it compiles successfully. 

![screen shot 2016-07-31 at 21 33 32](https://cloud.githubusercontent.com/assets/200119/17278455/a18ee5f8-5766-11e6-883d-693cb99f84b3.png)

May be it would be better to always have server url.

**Comment by themre** [comment]
yes, when using Atom's terminal, I see this, however it still doesn't work, no warmings, but in Windows CMD I don't get URL, only warnings.

**Comment by d4rkr00t** [comment]
Oh, ok, I see. It's because when there are any warnings url doesn't show up. I'll fix it.

**Comment by d4rkr00t** [comment]
Hi, 
I just published version 0.6.0, can you please check whether it's still an issue?

**Comment by themre** [comment]
Yes, it works, thanks! Now I just needed to install globally eslint and babel-eslint. Now I need to read docs for material-ui, since they changed theming. You need to provide ThemeProvider when using for example AppBar. Oh well... :)

**Comment by d4rkr00t** [comment]
Why do you need global eslint and babel-eslint? They should work out of the box :)

**Comment by themre** [comment]
If I just run it, I get:
`Error in Cannot find module 'eslint'
 @ multi app`

**Comment by d4rkr00t** [comment]
Mmm, ok :( It should work. I'll fix it :)

**Comment by d4rkr00t** [comment]
Fixed.

Thank you so much for bug reports they helped a lot. Now I know that aik works on windows 10 :)
