### ISSUE TITLE
Include sass support

### ISSUE THREAD

**Issue by themre** [d4rkr00t/aik#79]
I think it would be very nice to include SASS support.

**Comment by d4rkr00t** [comment]
Have you seen [precss](https://github.com/jonathantneal/precss) plugin for postcss? It covers most important sass features (at least for me):
- Variables
- Nested rules
- Mixins
- Conditions

Furthermore I'm not a big fan of sass and there were some issues related to that sass uses native module. 

I think, at least for now, would be better to use postcss plugins than add one more dependency with extra configuration and possibly introducing more bugs.

**Comment by themre** [comment]
ok, that's not a problem, however how do I use precss? :)
I tried `require('precss')({ /* options */ }).process("style.css", { parser: require('postcss-scss') });` and `require("style.css")` and in both cases (if I have some variables syntax in css), I get 
`Error in ./~/postcss/lib/previous-map.js
Module not found: Error: Cannot resolve module 'fs' in c:\git\aik-demo\node_modules\postcss\lib
resolve module fs in c:\git\aik-demo\node_modules\postcss\lib` ... and a bunch more.
Thanks for help! :)

**Comment by d4rkr00t** [comment]
Precss is working out of the box :) you can just use features described in precss readme in your css files without any extra configuration.
